// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SessionDemo.Models;

namespace SessionDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SessionDemo.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Classroom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classroom = "P3",
                            FirstName = "Adam",
                            LastName = "Aladin"
                        },
                        new
                        {
                            Id = 2,
                            Classroom = "P3",
                            FirstName = "Bob",
                            LastName = "Brumbál"
                        },
                        new
                        {
                            Id = 3,
                            Classroom = "P3",
                            FirstName = "Cyrus",
                            LastName = "Casper"
                        },
                        new
                        {
                            Id = 4,
                            Classroom = "P3",
                            FirstName = "Daniel",
                            LastName = "Drakula"
                        },
                        new
                        {
                            Id = 5,
                            Classroom = "P3",
                            FirstName = "Eve",
                            LastName = "Elektra"
                        },
                        new
                        {
                            Id = 6,
                            Classroom = "P3",
                            FirstName = "Filip",
                            LastName = "Frankenstein"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
